version: '3'

services:
  # object-detection:
  #   build:
  #     context: ./Object-Detection
  #     dockerfile: Dockerfile
  #   command: python /mmdetection/Object-Detection/app.py
  #   volumes:
  #     - ./Object-Detection:/mmdetection/Object-Detection
  #   ports:
  #     - 8000:8000
  image-classification:
    build:
      context: ./Image-Classification
      dockerfile: Dockerfile
    command: python /workspace/Image-Classification/app.py
    runtime: nvidia
    volumes:
      - ./Image-Classification:/workspace/Image-Classification
    # ports:
    #   - 8000:8000